const ACCESS_TOKEN = "FGSJDKIDXGBWFGHNFV";
const ACCESS_TOKEN_TIME_LIFE = "1h";
const REFRESH_TOKEN = "OIUTGHJDURYHZSBB";
const REFRESH_TOKEN_TIME_LIFE = "1d";

module.exports = {ACCESS_TOKEN,
     ACCESS_TOKEN_TIME_LIFE,
     REFRESH_TOKEN,
     REFRESH_TOKEN_TIME_LIFE}
